remote_blob_paths:
  container_name: "pre-auth-policies"
  raw_uploaded_files: "raw_attachments"
  processed_images: "processed_docs_images"
  remote_dir_base: "pa_proccesing_runs"

azure_openai:
  temperature: 0
  max_tokens: 3000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  seed: 5555